---

- name: "Install git package"
  yum:
    name: git
    state: present

- name: "Clone CCM repo"
  git:
    repo: https://github.com/riptano/ccm.git
    dest: /home/centos/ccm

- name: "Install CCM.."
  shell: /home/centos/ccm/setup.py install > /home/centos/ccm/ccm-install.log 2>&1
  args:
    executable: /bin/bash
    chdir: /home/centos/ccm
    creates: /home/centos/ccm/ccm-install.log
