---

# firewalld
- name: "Remove firewalld"
  yum:
    name: firewalld
    state: absent
  when: ((ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux") and ansible_distribution_major_version == "7")


# iptables-services
- name: "Remove iptables-services"
  yum:
    name: iptables-services
    state: absent
  when: ((ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux") and ansible_distribution_major_version == "7")
